name: "call_workflow_from_other_repo"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    uses: jbh043/InvokeGitHubActionsCaller/blob/main/.github/workflows/callerworkflow_directfile.yml@main
    with:
      Input1: "XYZ1"
      Input2: "XYZ2"
      Input3: "XYZ3"
      Input4: "XYZ4"
